/* Educational content + architecture definitions (shared by the interactive app and the video). */
/* =====================================================================
   DATA: component explanations (three depth levels) and architectures
   ===================================================================== */
export const PARTS_INFO: any = {
  block:{name:'Engine block', moves:'Static',
    simple:'The block is the engine\u2019s skeleton: one heavy casting that holds the cylinders and cradles the crankshaft. Almost everything else bolts to it.',
    technical:'Usually cast iron or aluminium (aluminium blocks often have iron liners or coated bores). It contains the cylinder bores, the saddles that hold the crankshaft\u2019s main bearings, and internal passages for coolant (the water jacket) and pressurised oil (the oil galleries).',
    deep:'Combustion pressure tries to push the head off the top of the engine and the crankshaft out of the bottom. The head bolts and main-bearing caps tie those two loads together through the block, so it works as a stressed frame. Designers trade weight against stiffness with choices like open vs closed deck (how much metal surrounds the top of the bores), bore spacing (which caps the maximum bore), and bedplates or girdles that stiffen the bottom end for high rpm or high boost.',
    why:'Pistons, crankshaft and head must stay aligned to hundredths of a millimetre while being hammered by combustion thousands of times a minute. Something rigid has to hold that geometry.',
    cycle:'Carries the combustion load on every power stroke. Coolant flowing through it removes the heat the cylinder walls absorb.',
    fails:'A cracked block (usually from severe overheating or frozen coolant) can leak coolant into the oil or cylinders. It normally means replacing the engine.',
    rel:['liner','crank','mainbearing','head','pan']},
  liner:{name:'Cylinder (bore)', moves:'Static',
    simple:'The cylinder is the precisely machined tube the piston slides in. It is where the air\u2013fuel mixture is squeezed and burned.',
    technical:'The wall is honed with a fine cross-hatch pattern that holds a thin oil film for the rings. It can be the block material itself, a pressed-in iron liner, or a sprayed coating. Bore diameter, stroke and cylinder count together define displacement (try it in the Lab).',
    deep:'The bore must stay round and straight when hot and when the head bolts are tightened; builders even hone with a \u201ctorque plate\u201d bolted on to mimic that distortion. The volume left above the piston at top dead centre (the combustion chamber) sets the compression ratio together with the swept volume: CR = (V_swept + V_chamber) / V_chamber.',
    why:'Burning gas only does useful work if it is trapped and pushes on something that can move. The cylinder is that sealed chamber with one movable wall: the piston.',
    cycle:'Contains all four strokes. Its walls get very hot during combustion, and coolant around them carries that heat away.',
    fails:'A scored or worn bore lets combustion gas leak past the rings (blow-by) and oil leak into the chamber: lost compression, oil consumption, blue smoke.',
    rel:['piston','rings','block','head']},
  head:{name:'Cylinder head', moves:'Static',
    simple:'The head is the lid on the cylinders. It forms the roof of each combustion chamber and holds the valves, spark plugs and injectors.',
    technical:'It contains the intake and exhaust ports (passages leading to the valves), valve seats and guides, and in overhead-cam engines the camshaft bearings. Coolant passages keep the chamber roof and the exhaust valve seats from overheating.',
    deep:'Much of an engine\u2019s breathing character lives in the head: port shape and size, valve area, valve angle and chamber shape decide how much air it can flow at high rpm and how quickly the flame spreads. This model is a cross-flow head: intake on one side, exhaust on the other, so fresh charge sweeps straight across the chamber.',
    why:'The cylinder has to be sealed at the top, yet air must get in and exhaust must get out on a precise schedule. The head is a sealed lid that also contains those doors.',
    cycle:'Its valves open for intake and exhaust and stay shut through compression and power, when the head takes the full combustion pressure.',
    fails:'Overheating can warp the head so the gasket no longer seals: coolant loss, white exhaust smoke, further overheating.',
    rel:['gasket','intakevalve','exhaustvalve','plug','injector','camshaft']},
  gasket:{name:'Head gasket', moves:'Static',
    simple:'A thin seal squeezed between head and block. It keeps combustion gas in the cylinder and keeps oil and coolant in their own passages.',
    technical:'Modern gaskets are multi-layer steel (MLS) with raised beads around each bore. One joint must seal combustion gas at tens of bar (well over 100 bar in high-output engines), coolant and oil, while head and block expand at different rates.',
    deep:'The head-bolt clamp load is what really seals the joint; the gasket concentrates it. High boost or knock can momentarily lift the head and push gas past the fire ring, which is why high-output engines use more or stronger head fasteners and reinforced fire rings.',
    why:'Two large castings can never be machined perfectly flat and stay that way when hot. A compressible seal fills the microscopic gaps.',
    cycle:'Every combustion event tries to force gas between head and block. The gasket holds it back.',
    fails:'A \u201cblown\u201d head gasket mixes things that should stay apart: coolant in the cylinder (white smoke), combustion gas in the cooling system (bubbling, overheating), or oil mixing with coolant.',
    rel:['head','block','liner']},
  cover:{name:'Cam cover', moves:'Static',
    simple:'The lid over the camshafts. It keeps the oil that splashes around the valvetrain inside the engine and dirt out.',
    technical:'Usually aluminium, magnesium or plastic composite. It often carries the crankcase-ventilation oil separator and the oil filler cap, and on many engines the ignition coils sit on or through it.',
    deep:'It carries no structural load, so designers use it for noise control (it is a large surface that radiates sound) and to separate oil mist from blow-by gases before those gases are routed back into the intake.',
    why:'The camshafts and valves run drenched in oil. Without a cover it would be flung out of the engine.',
    cycle:'Static. Oil sprays off the cams onto its underside and drains back down.',
    fails:'A leaking cover gasket is a common, mostly harmless oil leak, although oil dripping onto a hot exhaust can smoke or catch fire.',
    rel:['camshaft','head','tappet']},
  piston:{name:'Piston', moves:'Moves up and down',
    simple:'A piston is the moving plug inside the cylinder. Burning fuel and air pushes it down, and that push eventually becomes the rotation that turns the wheels.',
    technical:'Cast or forged aluminium. The crown faces the combustion; grooves below it carry the piston rings; the wrist pin (gudgeon pin) joins it to the connecting rod. The skirt stops it rocking in the bore.',
    deep:'A piston stops and reverses twice every revolution. With an 86 mm stroke at 7,000 rpm its peak acceleration near TDC is roughly 3,000 g, so every gram becomes a large inertial load (see the RPM experiment in the Lab). That is why high-revving engines favour short strokes, light forged pistons and short skirts. Turbocharged engines often add oil jets that cool the underside of the crown.',
    why:'Pressure is useless unless it pushes on something that can move. The piston is the movable wall that turns gas pressure into force.',
    cycle:'Moves down on intake (drawing air in), up on compression, is forced down on power, and moves up on exhaust (pushing gas out).',
    fails:'A hole melted in the crown (from knock or a lean mixture) destroys compression in that cylinder and pressurises the crankcase with combustion gas.',
    rel:['rings','rod','liner','crank']},
  rings:{name:'Piston rings', moves:'Move with the piston',
    simple:'Springy split rings around the piston. They seal the gap between piston and cylinder wall, keeping pressure above and oil below.',
    technical:'Usually three: a top compression ring, a second ring that both seals and scrapes oil, and an oil-control ring. They press outward against the bore by their own tension and, for the top ring, by gas pressure acting behind it.',
    deep:'Rings are a major source of engine friction, so modern rings are thin and low-tension. The top ring seals better under combustion pressure: gas gets into the groove behind the ring and pushes it against the bore and the groove\u2019s lower face.',
    why:'The piston cannot touch the cylinder wall: it expands with heat and would seize. There has to be a gap, and the rings seal it.',
    cycle:'They seal hardest during compression and power. The oil ring scrapes excess oil back down on every downstroke.',
    fails:'Worn or stuck rings mean low compression, blow-by and burning oil (blue smoke).',
    rel:['piston','liner']},
  rod:{name:'Connecting rod', moves:'Swings and reciprocates',
    simple:'The rod links the piston to the crankshaft. Its top end goes straight up and down; its bottom end goes round in a circle. That is how a straight-line push becomes rotation.',
    technical:'The small end holds the wrist pin; the big end is split, with a cap bolted around a crankpin and a plain bearing shell inside. Usually forged steel; titanium appears in some high-revving engines.',
    deep:'Because the rod works at an angle, the piston does not move as a pure sine wave: it moves faster in the half of its travel near TDC than near BDC. The ratio of rod length to crank radius sets how lopsided this is. That lopsidedness is the source of the \u201csecond-order\u201d vibration an inline-4 cannot cancel.',
    why:'The piston must move straight (it is in a tube) while the crankpin goes round. A link with a hinge at each end bridges the two.',
    cycle:'Compressed hard on the power stroke. Stretched at the top of the exhaust stroke, when inertia tries to pull the piston away from the crank; that tension load is what breaks rods when an engine over-revs.',
    fails:'A failed rod bearing or bolt can let the rod break and punch through the block (\u201cthrowing a rod\u201d).',
    rel:['piston','crank','rodbearing']},
  rodbearing:{name:'Rod bearing', moves:'Rides on the spinning crankpin',
    simple:'A thin, smooth shell between the rod\u2019s big end and the crankpin. It floats on a film of oil so metal never touches metal.',
    technical:'A plain bearing: steel-backed shells lined with a softer bearing alloy. Oil arrives through drillings in the crankshaft, fed from the main bearings.',
    deep:'It is a hydrodynamic bearing: the spinning pin drags oil into a wedge that builds pressure far above what the pump supplies, carrying very large loads on a film only micrometres thick. Lose oil supply and that film collapses within seconds.',
    why:'At these loads and speeds a pressurised oil film survives shock loading better and more compactly than rolling-element bearings.',
    cycle:'Load peaks on the power stroke and again at the top of the exhaust stroke.',
    fails:'Oil starvation leads to a spun bearing, then knocking, then possible rod failure.',
    rel:['rod','crank','oilpump']},
  crank:{name:'Crankshaft', moves:'Rotates (engine speed)',
    simple:'The crankshaft turns the pistons\u2019 up-and-down pushes into rotation. Each piston pushes on an offset \u201cthrow\u201d, much like a foot on a bicycle pedal.',
    technical:'A one-piece forged or cast steel shaft: main journals (the axis, running in the main bearings), crankpins offset by half the stroke (carrying the rods), webs joining them, and counterweights. The angles between the crankpins set the firing intervals.',
    deep:'The crankpin angles are the engine\u2019s DNA: a flat inline-4 crank has pins at 0\u00b0/180\u00b0/180\u00b0/0\u00b0, an inline-6 uses three pairs 120\u00b0 apart, a cross-plane V8 spaces its four pins 90\u00b0 apart. In this app the pin angles are not drawn by hand: they are calculated from each cylinder\u2019s bank angle and its place in the firing order, and the same numbers then drive every piston.',
    why:'Wheels need rotation; combustion only provides pushes. The crank converts a series of pushes into continuous turning.',
    cycle:'Turns twice per complete four-stroke cycle (720\u00b0). It speeds up slightly on each power stroke and slows on each compression stroke; the flywheel evens this out.',
    fails:'Oil starvation wears the journals; torsional vibration can crack long crankshafts, which is why many have a damper on the front.',
    rel:['rod','mainbearing','flywheel','timing','rodbearing']},
  mainbearing:{name:'Main bearings', moves:'Static shells; the crank spins inside',
    simple:'The bearings the crankshaft spins in. They hold the crank in the block while letting it turn on a film of oil.',
    technical:'Split shell bearings clamped by main caps or a bedplate. Oil from the main gallery reaches them first, then flows through drillings in the crank to the rod bearings. One main usually has thrust faces that locate the crank lengthwise.',
    deep:'Inline-6 engines traditionally have seven main bearings, one between every throw, which helps make them stiff and smooth. Fewer mains make a shorter, lighter crank that flexes more.',
    why:'The crank carries every combustion load into the block and needs support at several points along its length.',
    cycle:'Loaded on every power stroke and continuously by the rotating mass.',
    fails:'Low oil pressure leads to wear, knocking and eventually seizure.',
    rel:['crank','block','oilpump']},
  camshaft:{name:'Camshaft', moves:'Rotates at half engine speed',
    simple:'A shaft with egg-shaped lobes. As it turns, each lobe pushes a valve open, then lets the spring close it again. It keeps the engine\u2019s breathing schedule.',
    technical:'Driven from the crankshaft by chain, belt or gears at exactly half crank speed. This model uses double overhead cams (DOHC): one camshaft for the intake valves and one for the exhaust valves on each bank. The lobe shape sets how far (lift) and for how long (duration) each valve opens.',
    deep:'Each valve opens once per cycle, and a cycle takes two crank revolutions, so the cam turns once per cycle. The lobes in this model are generated from the same lift curve that moves the valves, so the lobe you see pressing the follower is exactly the lift plotted in the timeline. Variable valve timing rotates the cam relative to its sprocket to shift these events with rpm and load.',
    why:'Valves must open and close at precise crank angles thousands of times a minute. A cam mechanically locked to the crank does that without drifting.',
    cycle:'The intake lobe opens its valve around TDC and holds it through the intake stroke. The exhaust lobe opens its valve near the end of the power stroke and through the exhaust stroke.',
    fails:'If the timing drive breaks the cams stop and the engine dies; in \u201cinterference\u201d engines pistons can then strike open valves.',
    rel:['tappet','intakevalve','exhaustvalve','timing','head']},
  intakevalve:{name:'Intake valve', moves:'Opens and closes',
    simple:'The door that lets fresh air (and fuel) into the cylinder. It opens for the intake stroke and stays shut the rest of the time.',
    technical:'A poppet valve: a disc on a stem, pulled onto a machined seat by its spring. It is usually larger than the exhaust valve because incoming air is pushed only by atmospheric (or boost) pressure, while exhaust leaves under high cylinder pressure.',
    deep:'It opens a little before TDC and closes well after BDC (about 12\u00b0 before TDC and 40\u00b0 after BDC in this model). The late close uses the momentum of the moving air to keep filling the cylinder after the piston starts rising: good at high rpm, slightly worse at low rpm. Variable valve timing and lift systems such as Honda\u2019s VTEC exist to adjust that compromise.',
    why:'The cylinder must be sealed for compression and power but open for filling. A valve is a door that can seal against very high pressure.',
    cycle:'Open from about 708\u00b0 through 0\u00b0 to 220\u00b0 in this model\u2019s cycle.',
    fails:'A valve stuck shut starves the cylinder (misfire). A bent or burnt valve leaks compression.',
    rel:['camshaft','tappet','spring','head','intake']},
  exhaustvalve:{name:'Exhaust valve', moves:'Opens and closes',
    simple:'The door that lets burned gas out. It opens near the end of the power stroke and through the exhaust stroke.',
    technical:'A poppet valve like the intake valve, but it runs much hotter because hot exhaust flows past it. High-performance exhaust valves may use heat-resistant alloys or sodium-filled stems to carry heat away.',
    deep:'It opens about 40\u00b0 before BDC in this model. Giving up the last bit of expansion lets the remaining pressure blow most of the exhaust out on its own (\u201cblowdown\u201d), so the piston does less work pushing it out. It closes just after TDC, overlapping with the intake opening.',
    why:'Burned gas has to leave so fresh charge can enter. It needs its own door because the intake side is cool and the exhaust side is very hot.',
    cycle:'Open from about 500\u00b0 to 12\u00b0 (into the next cycle) in this model.',
    fails:'A burnt exhaust valve leaks compression and causes a persistent misfire in that cylinder.',
    rel:['camshaft','tappet','spring','head','exhaust']},
  spring:{name:'Valve spring', moves:'Compresses and extends',
    simple:'The spring snaps the valve shut after the cam lobe has passed.',
    technical:'It must close the valve quickly enough to follow the cam\u2019s closing ramp at the engine\u2019s highest rpm. Too weak and the valve \u201cfloats\u201d; too stiff and it adds friction and wear.',
    deep:'Valve float is often what really limits how fast a production engine can rev. Formula 1 engines replaced steel springs with pneumatic springs (compressed nitrogen) to rev far higher.',
    why:'A cam lobe can only push. Something has to pull the valve back onto its seat.',
    cycle:'Compressed while its valve is open, pushing it closed as the lobe passes.',
    fails:'A broken spring leaves the valve hanging open: misfire, or even valve-to-piston contact.',
    rel:['intakevalve','exhaustvalve','tappet']},
  tappet:{name:'Bucket tappet', moves:'Moves up and down',
    simple:'A small cup on top of the valve. The cam lobe slides across it and pushes it, and the valve, downward.',
    technical:'It turns the cam\u2019s rotating push into straight-line motion and absorbs the sideways scrubbing so the valve stem doesn\u2019t. Other designs use roller finger followers or rocker arms; pushrod engines keep the cam in the block and use pushrods and rockers.',
    deep:'Direct-acting buckets are very stiff (good for high rpm) but have high sliding friction; roller followers cut friction and make variable-lift mechanisms possible. Valve clearance is set with shims or taken up automatically by hydraulic lifters.',
    why:'The cam lobe slides sideways across its contact point; the valve stem must only move straight.',
    cycle:'Follows the lobe profile: it moves only while the lobe\u2019s nose passes.',
    fails:'Too much clearance causes ticking; too little keeps the valve from fully closing, which burns it.',
    rel:['camshaft','spring','intakevalve','exhaustvalve']},
  timing:{name:'Timing chain and sprockets', moves:'Rotates',
    simple:'The chain ties the camshafts to the crankshaft so the valves always open at the right piston position. The cam sprockets have twice as many teeth as the crank sprocket, so they turn at half speed.',
    technical:'It can be a chain, a toothed belt or a gear train, with tensioners and guides keeping it tight. Watch the marks on the sprockets: the crank mark goes round twice for each turn of a cam mark.',
    deep:'In \u201cinterference\u201d engines valves and pistons occupy the same space at different times, and only the timing drive keeps them apart. Chains usually last the life of the engine; belts need periodic replacement. Real four-cam V engines often use several chains; this model simplifies them into one loop.',
    why:'Valve timing must stay locked to crank position. A direct mechanical link never drifts.',
    cycle:'Runs continuously at a fixed 2:1 ratio.',
    fails:'A stretched chain retards cam timing (rattle, warning light). A snapped chain or belt stops the engine and can bend valves.',
    rel:['crank','camshaft','tcover']},
  tcover:{name:'Timing cover', moves:'Static',
    simple:'A cast lid over the front of the engine. It hides the timing chain and keeps the oil that lubricates it inside.',
    technical:'Usually cast aluminium, bolted to the front of the block and head with a gasket. It carries the crankshaft’s front oil seal, and often mounts the chain tensioner, the water pump or the oil pump.',
    deep:'The chain runs in oil mist, so the cover has to seal around a spinning crankshaft. A lip seal rides on the crank’s nose (or on the pulley hub), and the harmonic damper bolted in front of it tames the crank’s twisting vibration.',
    why:'The timing drive needs oil and needs protecting from dirt and fingers, but it also has to be reachable for service.',
    cycle:'Static. The chain and sprockets turn behind it; the crank pulley turns in front of it.',
    fails:'A leaking front crank seal drips oil onto the drive belts. A cracked cover can let oil out or coolant in.',
    rel:['timing','crank','block']},
  plug:{name:'Spark plug and coil', moves:'Fires once per cycle',
    simple:'The spark plug makes a tiny lightning bolt inside the cylinder that ignites the compressed air\u2013fuel mixture.',
    technical:'The ignition coil, commanded by the engine computer (ECU), sends tens of thousands of volts across the plug\u2019s electrode gap. The spark fires before TDC (about 15\u00b0 here) because the flame needs time to spread.',
    deep:'Timing is tuned for the least advance that gives the best torque, which puts peak pressure a little after TDC. Too much advance risks knock (unburned end gas auto-igniting); too little and pressure peaks late, sending energy out the exhaust as heat. Knock sensors let the ECU run close to that limit.',
    why:'A gasoline\u2013air mixture in a spark-ignition engine needs a precisely timed ignition source; relying on compression heat alone is how a diesel works.',
    cycle:'Fires once per cycle, near the end of compression.',
    fails:'A worn plug or failed coil causes a misfire: rough running and unburned fuel reaching the exhaust, which can overheat the catalytic converter.',
    rel:['head','injector']},
  injector:{name:'Fuel injector and rail', moves:'Opens briefly each cycle',
    simple:'An electrically controlled nozzle that sprays a precise amount of fuel. The ECU decides how much, based on how much air is coming in.',
    technical:'This model shows direct injection: fuel at very high pressure (hundreds of bar in many gasoline systems) sprayed straight into the cylinder during the intake stroke. Many engines use port injection instead, spraying at a few bar into the intake port just upstream of the valve.',
    deep:'Gasoline burns cleanly near the stoichiometric ratio of about 14.7 parts air to 1 part fuel by mass. The ECU measures the incoming air (airflow or manifold-pressure sensor), calculates fuel, then trims it using the oxygen sensor in the exhaust. Direct injection cools the charge as fuel evaporates inside the cylinder, which allows more compression or boost before knock.',
    why:'The throttle controls air; fuel has to be metered to match it for complete, clean combustion.',
    cycle:'Sprays during the intake stroke in this model.',
    fails:'A clogged injector runs its cylinder lean (misfire, heat); a leaking one runs it rich.',
    rel:['intake','plug','head']},
  intake:{name:'Intake manifold', moves:'Static; air flows through it',
    simple:'Tubes (runners) that share out incoming air from a common chamber (the plenum) to each cylinder.',
    technical:'Runner length and diameter are tuned: pressure waves travelling up and down each runner can arrive at the intake valve just as it closes and push in extra air. Long runners help low-rpm torque, short runners help high rpm, and some engines switch between them.',
    deep:'This is resonance or ram tuning: breathing is a wave problem, not just a pipe of air. A well-tuned naturally aspirated engine can exceed 100% volumetric efficiency in its tuned rpm range.',
    why:'Every cylinder needs an equal share of air arriving from a single throttle.',
    cycle:'Air in each runner surges when that cylinder\u2019s intake valve opens and stalls when it closes. Turn on the Air flow to see it.',
    fails:'A vacuum leak lets in unmeasured air: lean running, rough idle.',
    rel:['throttle','intakevalve','filter','injector']},
  throttle:{name:'Throttle body', moves:'Its flap rotates with the accelerator',
    simple:'A rotating flap. Your accelerator pedal really controls this: open it and more air gets in, the engine adds fuel to match, and power rises.',
    technical:'Gasoline engines control power mainly by restricting air, with fuel following. Modern throttles are electronic: the pedal is a sensor and the ECU positions the flap with a motor.',
    deep:'Throttling leaves a partial vacuum in the manifold, so at part load the pistons do \u201cpumping work\u201d pulling against it, a significant efficiency loss. Diesels (unthrottled) and systems that control air with valve lift instead, such as BMW Valvetronic, reduce that loss.',
    why:'A gasoline engine needs a nearly fixed air\u2013fuel ratio, so to make less power it must take in less air.',
    cycle:'This model runs at full throttle, flap wide open.',
    fails:'A dirty or faulty throttle can cause stalling, rough idle or a reduced-power mode.',
    rel:['intake','filter']},
  filter:{name:'Air filter', moves:'Static',
    simple:'Cleans the air before the engine swallows it. Engines breathe thousands of litres a minute, and dust would quickly wear the cylinders.',
    technical:'A paper or cotton element in a housing. The airflow sensor usually sits just downstream.',
    deep:'A 2.0-litre four-stroke at 6,000 rpm and full load takes in about 6,000 litres of air a minute (displacement \u00d7 rpm \u00f7 2, at 100% volumetric efficiency). Filter design balances catching particles against restricting flow.',
    why:'Abrasive dust entering the cylinders would wear rings and bores rapidly.',
    cycle:'Air flows through it whenever the engine runs.',
    fails:'A clogged filter reduces power at high load; a torn one lets dust in.',
    rel:['throttle','intake']},
  exhaust:{name:'Exhaust manifold', moves:'Static; exhaust flows through it',
    simple:'Collects hot burned gas from each cylinder and routes it to the rest of the exhaust: catalytic converter, silencers, tailpipe.',
    technical:'Compact cast-iron \u201clog\u201d manifolds are durable; tubular headers with tuned, often equal-length runners let pressure pulses help empty each cylinder.',
    deep:'Each exhaust pulse racing down a runner leaves a low-pressure wave behind it that can help pull out the next cylinder\u2019s gas, especially during valve overlap. How runners are paired by firing order is one reason exhaust design, not just cylinder count, shapes an engine\u2019s sound.',
    why:'Exhaust leaves each cylinder at several hundred degrees in sharp pulses. It must be collected and piped safely away.',
    cycle:'Gas in each runner surges when that cylinder\u2019s exhaust valve opens. Turn on the Exhaust flow to see it.',
    fails:'A cracked manifold makes a ticking leak and can upset oxygen-sensor readings.',
    rel:['exhaustvalve','head']},
  pan:{name:'Oil pan (sump)', moves:'Static',
    simple:'The reservoir at the bottom of the engine that holds the oil. Oil drains into it and the pump picks it up from here.',
    technical:'Pressed steel or cast aluminium, with baffles that stop oil sloshing away from the pickup in hard cornering.',
    deep:'Many racing engines use a dry sump: scavenge pumps empty the crankcase into a separate tank. That stops oil starvation in corners, reduces the drag of oil being whipped by the crank, and lets the engine sit lower in the car.',
    why:'Oil needs somewhere to collect, cool slightly and settle before being pumped around again.',
    cycle:'Oil returns here continuously from the bearings and the head.',
    fails:'A holed sump drains the oil; bearings fail within minutes of losing oil pressure.',
    rel:['oilpump','crank','block']},
  oilpump:{name:'Oil pump', moves:'Rotates with the crank',
    simple:'Pumps oil from the sump through the filter and into passages that feed every bearing and the valvetrain.',
    technical:'Gear, rotor (gerotor) or vane type, driven by the crankshaft. This model shows a gerotor mounted on the crank nose. Many modern pumps vary their output to save fuel.',
    deep:'Flow matters more than pressure: the bearings generate their own film pressure, and the pump\u2019s job is to keep them flooded with fresh, cool oil. Oil also carries heat away from bearings and, via jets, from the pistons.',
    why:'Splash alone cannot reliably reach every bearing at every speed.',
    cycle:'Turns continuously at crank speed.',
    fails:'Pump failure means rapid bearing wear. An oil-pressure warning light means stop the engine immediately.',
    rel:['pan','mainbearing','rodbearing','crank']},
  flywheel:{name:'Flywheel', moves:'Rotates with the crank',
    simple:'A heavy disc on the back of the crankshaft. It stores rotational energy between power strokes so the engine turns smoothly instead of lurching.',
    technical:'It also carries the starter ring gear and, with a manual gearbox, is the friction face for the clutch. Automatics use a light flexplate, with the torque converter adding inertia.',
    deep:'Fewer cylinders mean bigger gaps between power strokes and more flywheel needed; a single-cylinder engine depends on it heavily, a V12 far less. A lighter flywheel lets revs rise and fall faster (sharper response) at the cost of smoothness at idle.',
    why:'Combustion arrives in pulses. For most of the cycle each cylinder is actually absorbing energy (compression and pumping), so inertia has to carry the crank through.',
    cycle:'Absorbs energy on each power stroke and gives it back during the others.',
    fails:'Worn dual-mass flywheels rattle and cause clutch judder.',
    rel:['crank']}
};

/* ---- Engine architectures. Cylinders: n = number, b = bank index, z = position along crank (pitch ~100 mm).
   Crankpin angles are DERIVED from bank angle + firing order (see deriveEngine), not hard-coded. ---- */
export const ARCHS: any = {
  single:{name:'Single', full:'Single cylinder', banks:[0], cyl:[{n:1,b:0,z:0}], firing:[1],
    tagline:'The whole four-stroke story in its simplest form: one cylinder, one power stroke every two revolutions.',
    layout:'One vertical cylinder', crank:'One throw with a large counterweight', interval:'720\u00b0 (one power stroke every two revolutions)',
    balance:'Poor. The piston\u2019s back-and-forth motion shakes the engine; counterweights and often a balance shaft reduce it.',
    packaging:'Very compact and light.', character:'Strong individual pulses; needs a heavy flywheel to idle smoothly.',
    uses:'Motorcycles, scooters, small equipment.',
    pros:['Simplest, lightest, cheapest','Few moving parts, easy to maintain','Large single cylinder gives good low-speed pull for its size'],
    cons:['Large torque pulses and vibration','Hard to make big: one huge cylinder is slow to burn and heavy to reciprocate','Needs a heavy flywheel'],
    why:[['Why not just build one huge cylinder?','Because big pistons are heavy (inertial loads rise with mass \u00d7 rpm\u00b2), the flame takes longer to cross a big bore, and one power stroke per 720\u00b0 makes enormous pulses. Splitting the same displacement into several smaller cylinders lets the engine rev higher, burn faster and deliver smoother torque. Compare the smoothness chart against an inline-4.']],
    examples:[{e:'KTM 690 LC4', spec:'690 cc single, naturally aspirated', cars:'KTM 690 Duke / Enduro motorcycles', why:'A modern large single that relies on balance shafts to keep its vibration in check.'}]},
  i4:{name:'Inline-4', full:'Inline-4', banks:[0], cyl:[1,2,3,4].map((n,i)=>({n,b:0,z:i})), firing:[1,3,4,2],
    tagline:'The default engine of the modern world: four cylinders in a row on a flat crankshaft.',
    layout:'Four cylinders in one straight row', crank:'Flat: pins at 0\u00b0, 180\u00b0, 180\u00b0, 0\u00b0 (four throws, usually five main bearings)', interval:'180\u00b0 (a power stroke every half revolution)',
    balance:'The pistons\u2019 main (first-order) forces cancel, but a second-order vertical shake at twice crank speed does not; larger inline-4s often add twin balance shafts.',
    packaging:'Short enough to mount sideways (transverse) in front-wheel-drive cars; one cylinder head keeps cost down.',
    character:'Busy, even pulses. Can rev very high when built for it.',
    uses:'Most compact and mid-size cars, many sports cars, motorcycles.',
    pros:['Compact, cheap, one head and one set of camshafts','Fits sideways in front-wheel-drive cars','Takes turbocharging very well'],
    cons:['Second-order vibration grows with size, so most stay near 2.5 L or below','Power pulses have gaps (no overlap), less smooth than 6+ cylinders'],
    why:[['Why is the inline-4 so common?','It\u2019s the smallest layout with a power stroke every half revolution and inherently cancelling first-order forces, using just one head. That\u2019s the best balance of smoothness, cost and size for everyday cars.'],['Why does it vibrate at all if it\u2019s \u201cbalanced\u201d?','Pistons 1 and 4 move exactly opposite 2 and 3, but because of rod angularity the pistons at the top of their stroke move faster than the ones at the bottom. The forces don\u2019t quite cancel, leaving a vertical shake twice per revolution. Balance shafts spinning at twice crank speed cancel it.']],
    examples:[
      {e:'Honda F20C', spec:'2.0 L, naturally aspirated, 87 \u00d7 84 mm, 9,000 rpm redline (early versions)', cars:'Honda S2000 (AP1)', why:'Short stroke, light internals and VTEC let a road-car four rev like a racing engine. Its peak power arrives near the top of the rev range.'},
      {e:'Mitsubishi 4G63T', spec:'2.0 L turbocharged', cars:'Lancer Evolution I\u2013IX', why:'A strong iron block and balance shafts made it tough enough for rallying and very high boost.'},
      {e:'Volkswagen EA888', spec:'2.0 L turbocharged, direct injection', cars:'Golf GTI and many VW Group models', why:'Shows the modern recipe: small displacement, turbo and direct injection for strong low-rpm torque and good efficiency.'}]},
  i6:{name:'Inline-6', full:'Inline-6', banks:[0], cyl:[1,2,3,4,5,6].map((n,i)=>({n,b:0,z:i})), firing:[1,5,3,6,2,4],
    tagline:'Six in a row: the layout famous for being inherently smooth.',
    layout:'Six cylinders in one straight row', crank:'Three pairs of pins 120\u00b0 apart, front half mirroring the rear (typically seven main bearings)', interval:'120\u00b0 (power strokes overlap)',
    balance:'Excellent. First- and second-order forces and the rocking couples all cancel, because the front three cylinders mirror the rear three.',
    packaging:'Long. Usually mounted lengthwise, driving the rear wheels; the long crank must be stiff.',
    character:'Silky, even and turbine-like, with overlapping power strokes.',
    uses:'BMW, Toyota, Nissan and Mercedes-Benz sports and luxury cars, trucks.',
    pros:['Near-perfect balance without balance shafts','One cylinder head, simple exhaust routing','Overlapping power strokes: very smooth torque'],
    cons:['Long engine is hard to fit, especially sideways','Long crank and camshafts are prone to twisting (torsional) vibration'],
    why:[['Why is an inline-6 so smooth?','Think of it as two inline-3s joined back to back, mirror images of each other. Each three-cylinder half cancels its first- and second-order forces by itself, and the mirroring cancels the rocking. Nothing is left to shake.'],['Why is a V6 packaged differently?','A V6 folds the same six cylinders into two short banks, so the engine is roughly half as long and fits sideways in a front-wheel-drive car, but it needs two heads and loses the inline-6\u2019s natural balance.']],
    examples:[
      {e:'BMW S54', spec:'3.2 L, naturally aspirated, 8,000 rpm redline', cars:'BMW M3 (E46)', why:'Individual throttle bodies and a high rev limit showed how freely a well-built inline-6 can rev.'},
      {e:'Toyota 2JZ-GTE', spec:'3.0 L twin-turbo', cars:'Toyota Supra (A80)', why:'A very robust iron block made it famous for handling much more boost than stock.'},
      {e:'Nissan RB26DETT', spec:'2.6 L twin-turbo', cars:'Nissan Skyline GT-R (R32\u2013R34)', why:'Built to homologate a racing car; paired with all-wheel drive to dominate touring-car racing.'},
      {e:'Mercedes-Benz M256', spec:'3.0 L turbocharged, 48 V mild hybrid', cars:'Mercedes-Benz S-Class and others', why:'A modern return to the inline-6, with an electric starter-generator helping at low rpm.'}]},
  v6:{name:'V6', full:'60\u00b0 V6', banks:[30,-30],
    cyl:[{n:1,b:0,z:0},{n:2,b:1,z:.5},{n:3,b:0,z:1.1},{n:4,b:1,z:1.6},{n:5,b:0,z:2.2},{n:6,b:1,z:2.7}], firing:[1,2,3,4,5,6],
    tagline:'Six cylinders folded into two banks of three: shorter than an inline-6, wider and less naturally balanced.',
    layout:'Two banks of three cylinders at 60\u00b0', crank:'Each cylinder on its own crankpin (split-pin style) to give 120\u00b0 even firing', interval:'120\u00b0',
    balance:'Good but not perfect: each bank is an inline-3, leaving a rocking couple that counterweights (and sometimes a balance shaft) reduce.',
    packaging:'Short and fairly compact; fits sideways in front-wheel-drive cars. Needs two heads.',
    character:'Smooth and compact; sound varies widely with bank angle and exhaust design.',
    uses:'Front- and all-wheel-drive family cars, trucks, some sports cars.',
    pros:['Much shorter than an inline-6','Fits transversely','Stiff, short crankshaft'],
    cons:['Two heads and more camshafts: more parts and cost','Rocking imbalance needs counterweights or a balance shaft','Wider than an inline engine'],
    why:[['Why 60\u00b0?','With 720\u00b0 \u00f7 6 = 120\u00b0 between firings, a 60\u00b0 bank angle lets pins be arranged for perfectly even firing while keeping the engine narrow. 90\u00b0 V6s (often derived from V8 tooling) need offset \u201csplit\u201d crankpins to fire evenly.'],['Why choose a V6 over an inline-6?','Length. A transverse front-wheel-drive car simply doesn\u2019t have room for six cylinders in a row.']],
    examples:[
      {e:'Nissan VQ35DE', spec:'3.5 L 60\u00b0 V6, naturally aspirated', cars:'Nissan 350Z, Infiniti G35 and others', why:'Used in both front- and rear-wheel-drive cars, showing the V6\u2019s packaging flexibility.'},
      {e:'Nissan VR38DETT', spec:'3.8 L 60\u00b0 twin-turbo V6', cars:'Nissan GT-R (R35)', why:'A compact V6 with two turbos gave supercar performance in a four-seat car.'},
      {e:'Ford 3.5 EcoBoost', spec:'3.5 L 60\u00b0 twin-turbo V6', cars:'Ford F-150, Ford GT (2017)', why:'The same basic engine family replaced V8s in trucks and powered a Le Mans-winning race car.'}],
    note:'Model uses 1-2-3-4-5-6 firing with odd cylinders on one bank, as in GM\u2019s 60\u00b0 V6 family. Other V6s differ.'},
  v8:{name:'V8', full:'Cross-plane V8', banks:[45,-45],
    cyl:[{n:1,b:0,z:0},{n:2,b:1,z:.24},{n:3,b:0,z:1},{n:4,b:1,z:1.24},{n:5,b:0,z:2},{n:6,b:1,z:2.24},{n:7,b:0,z:3},{n:8,b:1,z:3.24}],
    firing:[1,8,4,3,6,5,7,2],
    tagline:'Two banks of four at 90\u00b0, sharing four crankpins. Big displacement in a short package.',
    layout:'Two banks of four cylinders at 90\u00b0', crank:'Cross-plane: four pins 90\u00b0 apart, each shared by one rod from each bank', interval:'90\u00b0 (power strokes always overlap)',
    balance:'Very good with heavy counterweights: forces cancel and the remaining rocking couple is cancelled by the counterweights.',
    packaging:'Short but wide and tall; usually lengthwise, driving the rear wheels.',
    character:'Deep torque and the familiar uneven \u201cburble\u201d from the exhaust.',
    uses:'American performance cars and trucks, luxury sedans, many supercars.',
    pros:['Large displacement in a short, stiff package','Four power strokes per revolution: strong, smooth torque','Very compatible with turbocharging and supercharging'],
    cons:['Heavy cross-plane crank limits how quickly it revs','Wide and tall; two heads','Uneven firing within each bank complicates exhaust tuning'],
    why:[['Why does a cross-plane V8 sound like that?','Viewed one bank at a time, the firing is uneven: in this 1-8-4-3-6-5-7-2 order, bank 1-3-5-7 fires 1, 3, 5, 7 at irregular gaps. When each bank has its own exhaust, those irregular pulses produce the typical burble. Flat-plane V8s fire each bank evenly and sound more like two four-cylinders. Exhaust design, intake and rpm all shape the sound too, so not every V8 sounds alike.'],['Why not a flat-plane V8?','A flat crank is lighter and gives even firing per bank (good for high rpm and exhaust tuning, as in many Ferrari V8s), but it keeps the inline-4\u2019s second-order vibration. Cross-plane trades rev-happiness for smoothness.']],
    examples:[
      {e:'GM LS3', spec:'6.2 L, naturally aspirated, pushrod (one camshaft in the block)', cars:'Chevrolet Corvette (C6), Camaro SS', why:'A compact pushrod design: large displacement with a low, narrow top end.'},
      {e:'Ford Coyote 5.0', spec:'5.0 L, naturally aspirated, DOHC', cars:'Ford Mustang GT (2011 on)', why:'Four camshafts and variable cam timing let a big V8 rev past 7,000 rpm.'},
      {e:'Ferrari F154 (flat-plane)', spec:'3.9 L twin-turbo, flat-plane crank', cars:'Ferrari 488 GTB, F8 Tributo', why:'A contrast case: the flat-plane crank and turbos give a very different character from an American cross-plane V8.'}],
    note:'Model uses GM numbering (odd cylinders on one bank) and the 1-8-4-3-6-5-7-2 order of GM\u2019s LS family. Ford and others number cylinders differently and use other orders. The model shows four overhead camshafts on every layout; the LS actually uses a single camshaft in the block with pushrods.'},
  flat6:{name:'Flat-6', full:'Flat-6 (boxer)', banks:[90,-90],
    cyl:[{n:1,b:0,z:0},{n:4,b:1,z:.5},{n:2,b:0,z:1.1},{n:5,b:1,z:1.6},{n:3,b:0,z:2.2},{n:6,b:1,z:2.7}], firing:[1,6,2,4,3,5],
    tagline:'Two banks of three lying flat and facing each other. Opposing pistons move apart and together like boxers\u2019 fists.',
    layout:'Two horizontal banks of three at 180\u00b0', crank:'Six pins; opposing cylinders\u2019 pins are 180\u00b0 apart so their pistons move in mirror image', interval:'120\u00b0',
    balance:'Excellent: opposing pistons cancel each other\u2019s forces; only a small rocking couple remains because opposite cylinders are slightly offset along the crank.',
    packaging:'Short and very low but wide. Low centre of gravity.',
    character:'Smooth, with a distinctive sound shaped by its exhaust layout.',
    uses:'Porsche 911 and some Boxster/Cayman models, Subaru six-cylinder models.',
    pros:['Very low centre of gravity','Short and inherently well balanced','Good fit behind or over an axle'],
    cons:['Wide: can limit steering lock and suspension space','Two heads and long exhaust/intake paths','Servicing (e.g. spark plugs) is awkward'],
    why:[['Why does a flat engine have a low centre of gravity?','The cylinders lie horizontally, so the heavy heads sit beside the crankshaft instead of above it. The whole mass sits lower, which helps handling.'],['Why are the pistons paired like that?','Each opposing pair uses crankpins 180\u00b0 apart, so both pistons move outward together and inward together. Their forces cancel directly, which is the source of the boxer\u2019s smoothness.']],
    examples:[
      {e:'Porsche 911 flat-six', spec:'Air-cooled then water-cooled, naturally aspirated and turbocharged versions', cars:'Porsche 911 (all generations)', why:'Mounted behind the rear axle, its short length made the rear-engine layout possible; its low height helps offset the unusual weight distribution.'},
      {e:'Subaru EZ36', spec:'3.6 L flat-6, naturally aspirated', cars:'Subaru Outback, Tribeca', why:'Subaru pairs boxer engines with symmetrical all-wheel drive; the low, short engine sits in line with the drivetrain.'}],
    note:'Model uses the classic Porsche order 1-6-2-4-3-5 with cylinders 1\u20133 on one bank.'}
};
export const ARCH_ORDER: any = ['single','i4','i6','v6','v8','flat6'];

/* ---- Valve timing & ignition in degrees of the cycle (0 = TDC at start of intake; 360 = firing TDC) ---- */
export const VT: any = { IVO:708, IVC:220, EVO:500, EVC:12, SPARK:345, INJ0:60, INJ1:140 };
export const PHASES: any = [
  {key:'intake', name:'Intake', from:0, to:180, color:'--air'},
  {key:'compression', name:'Compression', from:180, to:360, color:'--comp'},
  {key:'power', name:'Power', from:360, to:540, color:'--power'},
  {key:'exhaust', name:'Exhaust', from:540, to:720, color:'--exhaust'}
];
